### ISSUE TITLE
pipeline: 并发执行多条pipeline时，出现死锁

### ISSUE THREAD

**Issue by jayjiahua** [Tencent/bk-sops#1170]
问题描述
=======
创建了多条流水线，在同一时刻下发任务，某些任务会存在死锁现象，导致任务僵死，状态一直处于RUNNING。
本地测试结果：500条pipleine并发，会有 0~2条pipeline僵死。非必现，但出现频率较高

关键信息
=======
发生死锁的调用栈（已去掉路径前缀）

```
[2019-09-25 10:35:48,441: INFO/MainProcess] Received task: pipeline.engine.tasks.process_wake_up[a6a46f62-b36c-435d-a7a5-00993fe10e27]
[2019-09-25 10:35:48,444: ERROR/Worker-2] Traceback (most recent call last):
  File "pipeline/engine/core/runtime.py", line 51, in run_loop
    process.destroy_and_wake_up_parent(current_node.id)
  File "pipeline/engine/models/core.py", line 405, in destroy_and_wake_up_parent
    data_service.set_object(self._data_key(), self.top_pipeline.data)
  File "pipeline/engine/core/data/api.py", line 43, in set_object
    return __backend.set_object(key, obj)
  File "pipeline/engine/core/data/mysql_backend.py", line 23, in set_object
    return DataSnapshot.objects.set_object(key, obj)
  File "pipeline/engine/models/data.py", line 24, in set_object
    'obj': obj
  File "lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python2.7/site-packages/django/db/models/query.py", line 484, in update_or_create
    obj, created = self._create_object_from_params(lookup, params, lock=True)
  File "lib/python2.7/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "lib/python2.7/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
  File "lib/python2.7/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "lib/python2.7/site-packages/pymysql/connections.py", line 781, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "lib/python2.7/site-packages/pymysql/connections.py", line 942, in _read_query_result
    result.read()
  File "lib/python2.7/site-packages/pymysql/connections.py", line 1138, in read
    first_packet = self.connection._read_packet()
  File "lib/python2.7/site-packages/pymysql/connections.py", line 906, in _read_packet
    packet.check_error()
  File "lib/python2.7/site-packages/pymysql/connections.py", line 367, in check_error
    err.raise_mysql_exception(self._data)
  File "lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')

[2019-09-25 10:35:48,444: INFO/Worker-2] child process(d2f122a3c30c3d2983d0ac272822122a) finish.
```

**Comment by homholueng** [comment]
从堆栈上看是 mysql backend 导致的问题，建议先使用 redis backend 规避。
