### ISSUE TITLE
本地部署服务点击 "管理员入口" - "运营入口" 的 "流程引用" 时报错

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1364]
问题描述
=======
点击 "管理员入口" - "运营入口" 的 "流程引用" 时，前端报错500，后端查看日志显示：

```
ERROR [2019-11-06 14:22:24] /Users/jacky/Colstuwjx/Projects/IaaS/bk-sops/blueapps/core/exceptions/middleware.py 68 process_exception 30646 123145363038208
 	 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jacky/Colstuwjx/Projects/IaaS/bk-sops/gcloud/core/decorators.py", line 47, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/jacky/Colstuwjx/Projects/IaaS/bk-sops/gcloud/contrib/analysis/views.py", line 112, in query_template_by_group
    success, content = TaskTemplate.objects.extend_classified_count(result_dict['group_by'], filters, page_index, limit)
  File "/Users/jacky/Colstuwjx/Projects/IaaS/bk-sops/gcloud/tasktmpl3/models.py", line 336, in extend_classified_count
    for appmaker in appmaker_list:
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/db/models/query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 841, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch)
  File "/Users/jacky/.pyenv/versions/pybkops/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
InternalError: (1055, u"Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'bk_sops.appmaker_appmaker.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
], 请求URL->[/analysis/query_template_by_group/], 请求方法->[POST] 请求参数->[{"limit": "15", "pageIndex": "1", "group_by": "template_cite", "conditions": "{\"create_time\":1570377600000,\"finish_time\":1572969600000,\"order_by\":\"-templateId\"}"}]
```

重现方法
=======
如上，本地部署版本点击 ”流程引用“ 时会报错。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 3e1016e4
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by Colstuwjx** [comment]
原因已经找到，是本地的数据库未禁用 `ONLY_FULL_GROUP_BY ` 模式导致的
