### ISSUE TITLE
正式环境部署搜集前端资源报错

### ISSUE THREAD

**Issue by JuiceZZ** [Tencent/bk-sops#3044]
问题描述
=======
执行：python manage.py collectstatic --noinput
报错：
$ python manage.py collectstatic --noinput
Traceback (most recent call last):
  File "D:\App\Python36\lib\site-packages\django\core\management\__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\App\Python36\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\App\Python36\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\App\Python36\lib\site-packages\django\core\management\__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "D:\App\Python36\lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    self._setup(name)
  File "D:\App\Python36\lib\site-packages\django\conf\__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\App\Python36\lib\site-packages\django\conf\__init__.py", line 196, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by JuiceZZ** [comment]
V3.6.X

**Comment by normal-wls** [comment]
执行命令前没有加载对应的环境变量导致的。
