### ISSUE TITLE
快速执行脚本插件无法引用Job平台脚本，获取Job平台脚本列表失败

### ISSUE THREAD

**Issue by Weiney** [Tencent/bk-sops#5924]
关键信息
=======

- [  ] bk-sops 版本：3.24.3

问题描述
=======
业务新增标准运维流程，尝试使用官方插件执行快速执行脚本，新增节点后执行使用导入脚本，无法引用业务对应Job平台内的脚本，具体错误提示是：请求数据失败，报错截图如下：

![image](https://user-images.githubusercontent.com/33593246/183364881-d287c155-c2b8-4d92-9ca8-6d9d7bb4000c.png)

接口报错信息如下：
```
URL：*/o/bk_sops/pipeline/job_get_public_script_name_list/

Response：
{
  "result": false,
  "code": "50000",
  "message": "系统异常,请联系管理员处理",
  "data": null
}
```

容器报错日志(截取片段)：
```
ERROR [2022-08-08 14:27:19] /cache/.bk/env/lib/python3.6/site-packages/blueapps/core/exceptions/middleware.py 72 process_exception 6781 139703477454976
 	 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/app/code/pipeline_plugins/components/query/sites/open/job.py", line 85, in job_get_script_name_list
    if script["online_script_version_id"]:
KeyError: 'online_script_version_id'
], 请求URL->[/o/bk_sops/pipeline/job_get_script_name_list/3/], 请求方法->[GET] 请求参数->[{"type": "general"}] [trace_id]: 00-8ad68fb25b6211e90509b68d7df8ca47-2a276e44b0cd6dc2-01

ERROR [2022-08-08 14:42:20] /cache/.bk/env/lib/python3.6/site-packages/blueapps/core/exceptions/middleware.py 72 process_exception 6781 139703477454976
 	 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/app/code/pipeline_plugins/components/query/sites/open/job.py", line 94, in job_get_public_script_name_list
    if script["online_script_version_id"]:
KeyError: 'online_script_version_id'
], 请求URL->[/o/bk_sops/pipeline/job_get_public_script_name_list/], 请求方法->[GET] 请求参数->[{}] [trace_id]: 00-6115e00181fef0ffe973237e85643807-b5d8d18b98551af3-01

ERROR [2022-08-08 14:42:20] /cache/.bk/env/lib/python3.6/site-packages/blueapps/core/exceptions/middleware.py 72 process_exception 6781 139703477454976
 	 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/app/code/pipeline_plugins/components/query/sites/open/job.py", line 424, in jobv3_get_instance_list
    result_data = job_result["data"]["data"]
KeyError: 'data'
], 请求URL->[/o/bk_sops/pipeline/jobv3_get_instance_list/3/1/3/], 请求方法->[GET] 请求参数->[{}] [trace_id]: 00-06397992fb5f7a863e1975c184335bd5-cc1112cba7ddef88-01

ERROR [2022-08-08 15:42:01] /cache/.bk/env/lib/python3.6/site-packages/blueapps/core/exceptions/middleware.py 72 process_exception 6781 139703477454976
 	 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/app/code/pipeline_plugins/components/query/sites/open/job.py", line 94, in job_get_public_script_name_list
    if script["online_script_version_id"]:
KeyError: 'online_script_version_id'
], 请求URL->[/o/bk_sops/pipeline/job_get_public_script_name_list/], 请求方法->[GET] 请求参数->[{}] [trace_id]: 00-ad34bde9119250293c038eaed37e192f-e4ac340c8205ff87-01
```

问题在另外一个业务就正常，只有在这个业务会有问题，具体原因不详

本来以为是因为这个运维流程是从别的业务导出再导入进来引发的，但是后面发现即使新建依然存在。

看Json的报错应该是request返回的dict不包含执行的key引发异常的，具体没有打断点调试，不知道request具体返回。

重现方法
=======
因为问题是偶发的，所以我并不清楚怎么复现，但是我可以提供排查需要的相关数据。

End
======
**测试下来发现产品的Bug实在是有点多，这叫人如何放心往生产环境上推进呀**

**Comment by Weiney** [comment]
报错日志:
```
ERROR [2022-08-08 17:22:51] /cache/.bk/env/lib/python3.6/site-packages/blueapps/core/exceptions/middleware.py 72 process_exception 6781 139703477454976
 	 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/cache/.bk/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/app/code/pipeline_plugins/components/query/sites/open/job.py", line 112, in job_get_script_list
    if isinstance(script[value_field], int):
KeyError: 'online_script_version_id'
], 请求URL->[/o/bk_sops/pipeline/job_get_script_list/3/], 请求方法->[GET] 请求参数->[{"type": "public", "value_field": "online_script_version_id"}]
```

异常代码:
```
     def job_get_script_name_list(request, biz_cc_id):
         script_list = _job_get_scripts_data(request, biz_cc_id)
         script_names = []
         for script in script_list:
             if script["online_script_version_id"]:
                 script_names.append({"text": script["name"], "value": script["name"]})
         return JsonResponse({"result": True, "data": script_names})
```

看样子原因是因为script_list有一个item没有`online_script_version_id`这个key触发了Bug, 事实上这个业务确实有一个script没有这个key

**Comment by Weiney** [comment]
问题找到了, 为什么没有`online_script_version_id`这个key呢? 以为业务脚本列表有一个脚本没有没有上线, 就没有这个key

**Comment by normal-wls** [comment]
根据接口文档，对应接口的返回值中会有对应的字段，未上线版本值为空，所以我们会直接拿该字段的值来判断。
接口调用方对返回结果的每个key都进行存在性判断再取值，而且意味着每个调用方都需要这么做，这个方式不太合理。

我们已经联系job的同学，后续会处理解决该问题。

**Comment by Weiney** [comment]
> 根据接口文档，对应接口的返回值中会有对应的字段，未上线版本值为空，所以我们会直接拿该字段的值来判断。 接口调用方对返回结果的每个key都进行存在性判断再取值，而且意味着每个调用方都需要这么做，这个方式不太合理。
> 
> 我们已经联系job的同学，后续会处理解决该问题。

缺陷发生在当前系统，不能以为外部数据源的问题从而忽视系统本身的存在的缺陷，咱们系统内也应该要做好相应的风险管控，毕竟是相互独立的模块。

Dict、Map取值先判断存在，再取值应该是规范才对呀

**Comment by Weiney** [comment]
对应缺陷在ce.bktencent.com无法复现，不清楚是Bug已经被修复，还是说企业版和社区版存在差异

**Comment by normal-wls** [comment]
已提交兼容性pr，https://github.com/Tencent/bk-sops/pull/5933
