### ISSUE TITLE
ModuleNotFoundError: No module named 'client'

### ISSUE THREAD

**Issue by w940853815** [Tencent/bk-sops#611]
问题描述
=======

```
Collecting suds
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/d6/960acce47ee6f096345fe5a7d9be7708135fd1d0713571836f073efc7393/suds-
0.4.tar.gz

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/03/57k0m_xd5v59w75bl3p8g_lm0000gn/T/pip-install-jshxt1hl/suds/setup.py", line 20, in <module>
        import suds
      File "/private/var/folders/03/57k0m_xd5v59w75bl3p8g_lm0000gn/T/pip-install-jshxt1hl/suds/suds/__init__.py", line 154, in <mo
dule>
        import client
    ModuleNotFoundError: No module named 'client'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/03/57k0m_xd5v59w75bl3p8g_lm0000gn/T/pip
-install-jshxt1hl/suds/
```
重现方法
=======

anaconda python3.6
pip install -r requirements.txt

关键信息
=======
    ModuleNotFoundError: No module named 'client'

**Comment by pagezhou** [comment]
这个问题和 client 无关，是因为标准运维目前不支持 python3.6，请使用 python2.7 运行
py3的支持会在后续版本支持

**Comment by w940853815** [comment]
> 这个问题和 client 无关，是因为标准运维目前不支持 python3.6，请使用 python2.7 运行
> py3的支持会在后续版本支持

嗯,文档里也没说明使用的python是什么版本，建议说明一下

**Comment by pagezhou** [comment]
收到建议，我们在文档里加下说明
