### ISSUE TITLE
shell脚本中使用全局变更会引发异常

### ISSUE THREAD

**Issue by kevinpersist** [Tencent/bk-sops#713]
# 问题描述

标准运维-快速执行脚本
如果新建了全局变量`${ARG}`
shell脚本中如果使用了​`${ARG}`会导致执行异常，使用`$ARG`正常

# 重现方法

shell脚本中存在以`${xxx}`的形式的变量，其中`${xxx}`已是全局变量，执行任务时，会报异常，可重现

# 关键信息

![image](https://user-images.githubusercontent.com/10846583/61026314-8d00f800-a3e5-11e9-89da-d56e062e09d6.png)

![image](https://user-images.githubusercontent.com/10846583/61026322-925e4280-a3e5-11e9-9fd7-1fd82f195906.png)

请提供以下信息:

- [ ] bk-sops   版本 (发布版本号 或 git tag)： bk_sops_V3.3.13-ce
- [ ] 蓝鲸PaaS   版本：PaaS 3.2.511、PaaSAgent 3.1.0202
- [ ] bk_sops 异常日志：
  '''异常信息
  Traceback (most recent call last):
  File "./pipeline/engine/core/runtime.py", line 32, in runtime_exception_handler
  File "./pipeline/engine/core/runtime.py", line 112, in run_loop
  File "./pipeline/engine/core/handlers/base.py", line 31, in __call__
  File "./pipeline/engine/core/handlers/service_activity.py", line 64, in handle
  File "./pipeline/core/data/hydration.py", line 22, in hydrate_node_data
  File "./pipeline/core/data/hydration.py", line 31, in hydrate_data
  File "./pipeline/core/data/var.py", line 65, in get
  File "./pipeline/core/data/var.py", line 88, in _resolve
  File "./pipeline/core/data/expression.py", line 75, in resolve_data
  File "./pipeline/core/data/expression.py", line 126, in resolve_string
  File "./pipeline/core/data/expression.py", line 135, in resolve_template
  File "/data/bkce/paas_agent/apps/Envs/bk_sops/lib/python2.7/site-packages/mako/template.py", line 320, in __init__
  (code, module) = _compile_text(self, text, filename)
  File "/data/bkce/paas_agent/apps/Envs/bk_sops/lib/python2.7/site-packages/mako/template.py", line 711, in _compile_text
  code = compile(source, cid, 'exec')
  File "memory:0x7efc64f5d790", line 21
  return ''
  ^
  SyntaxError: invalid syntax'''

**Comment by pagezhou** [comment]
麻烦补充一下流程模板的JOB-快速执行脚本节点参数和全局变量的值，以便定位问题

**Comment by kevinpersist** [comment]
![image](https://user-images.githubusercontent.com/10846583/61505810-aa037f80-aa12-11e9-9d22-c3c6ed287e2a.png)


```bash
#!/bin/bash

set -e

usage() {
    echo "usage: ${0##*/} -l LOCATION "
    echo ""
    echo "OPTIONS list:"
    echo " -h    print this help page"
}

while getopts h:f:l:a:A:G:i:M: arg; do
    case $arg in
        h) usage ;;
        l) LOCATION="$OPTARG" ;;
        *) usage ;;
    esac
done

echo $LOCATION ## 如果把变量引用换成${LOCATION}，会报异常
```

**上面脚本可以正常执行，但如果把脚本中的变量引用换成${LOCATION}形式，会报异常**

**Comment by homholueng** [comment]
验证后发现是脚本中的 `${0##*/}` 这一段触发了变量替换的逻辑导致错误，请先尝试使用其他的方式绕过这个变量替换的逻辑，后续版本会修复。

**Comment by kevinpersist** [comment]
收到，感谢
